import type { Metadata } from "next";
import {  Bai_Jamjuree } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";


const BaiJamjuree = Bai_Jamjuree({ 
  subsets: ["latin"], 
  weight: ["200","300","400","500","600","700"], 
  variable: '--font-bai-jamjuree',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BaiJamjuree.variable} antialiased`}>
          <Header/>
          <PageTransition>{children}

          </PageTransition>



        
      </body>
    </html>
  );
}
